### ISSUE TITLE
plotting function

### ISSUE THREAD

**Issue by fawda123** [cbergmeir/RSNNS#2]
Hi there, 

I'm the author of the [NeuralNetTools](https://github.com/fawda123/NeuralNetTools) package.  I noticed your todo list for the next version of RSNNS links to an old gist of mine for plotting nnet objects.  The CRAN release for NeuralNetTools has a plotnet method for mlp models and I just pushed a feature to the devel version to plot pruned mlp models.  Thought you might be interested... I'll probably submit the latest release to CRAN pretty soon, so you could include it as a dependency in a future version of RSNNS.

Keep up the great work!

-Marcus

**Comment by cbergmeir** [comment]
Hi, thanks for the comment. I know your package, nice work! The problem I see is that we get a cyclic dependency but maybe that is ok if I just put your package in the suggests field...

**Comment by fawda123** [comment]
Hi and thanks for the reply.  I just pushed a commit that changed the dependencies for NeuralNetTools.  The package doesn't actually depend on RSNNS - not sure why I ever had it that way.
