### ISSUE TITLE
How to show the values of hidden nodes in a mlp model

### ISSUE THREAD

**Issue by AdDenissen** [cbergmeir/RSNNS#21]
Dear developer,

How can I predict the value of hidden nodes in a mlp model? 

For keras I can short the model upto a layer call 'dense_1' and make my predictions on 'ph.test':
layer_name <- 'dense_1';
chk_model <- keras_model(inputs=model$input, outputs=get_layer(model, layer_name)$output);
chko <- predict(chk_model, ph.test);

Thanks in advance,

Ad Denissen.

**Comment by cbergmeir** [comment]
Hi, in RSNNS, though it is possible, regretfully I don't think there is an easy way to do it. A good starting point will be demo/mlp_irisSnnsR.R . You have essentially three options. 

- Call saveNet(), I think that saves the activations of all units. Though you need to make sure that the last thing the network has seen is the pattern you are interested in. With predict(...) that should be possible, or one of the low level functions. 

- Another option would be to do something along the lines of the functions in R/SnnsR_extractNetInfo.R You'd have to call getUnitActivation(SEXP UnitNo) on every unit you are interested in.

- The third option is again to save the net and load it into javaNNS. That should allow you to see the activations.

**Comment by AdDenissen** [comment]
Hi,

Thanks for the tips. I used examples from SnnsR_extractNetInfo.R to fix the problem.

I can nicely observe the network activity based in the inputs.

Ad Denissen
Principal System Architect
Philips Research
Brain, Behaviour & Cognition
High Tech Campus 34 3.014
5656 AE Eindhoven
GSM. +31-6226-77777
________________________________

**Comment by cbergmeir** [comment]
Hi, 

I'm glad to hear you could get it to work.

Regards,
Christoph
