### ISSUE TITLE
R crashes upon running mlp()

### ISSUE THREAD

**Issue by bohmah** [cbergmeir/RSNNS#5]
Hi,

Can you look into the following issue? 

When I run mlp() I get the error 'terminate called after throwing an instance of 'Rcpp: not compatible' followed by a crash of R.

Thx.

**Comment by cbergmeir** [comment]
Hi,

this is most likely because you call mlp() with a data.frame instead of 
a matrix as input.

Regards,
Christoph

**Comment by caugusta** [comment]
I'm having a similar issue, and my input is indeed class matrix.

**Comment by cbergmeir** [comment]
Hi, can you give me more information; a reproducible example would be good. Are you using the newest version of RSNNS?
